const cities = [
  { "title": "New York, NY", "value": "New York, NY" },
  { "title": "Los Angeles, CA", "value": "Los Angeles, CA" },
  { "title": "Chicago, IL", "value": "Chicago, IL" },
  { "title": "Houston, TX", "value": "Houston, TX" },
  { "title": "Phoenix, AZ", "value": "Phoenix, AZ" },
  { "title": "Philadelphia, PA", "value": "Philadelphia, PA" },
  { "title": "San Antonio, TX", "value": "San Antonio, TX" },
  { "title": "San Diego, CA", "value": "San Diego, CA" },
  { "title": "Dallas, TX", "value": "Dallas, TX" },
  { "title": "San Jose, CA", "value": "San Jose, CA" },
  { "title": "Austin, TX", "value": "Austin, TX" },
  { "title": "Jacksonville, FL", "value": "Jacksonville, FL" },
  { "title": "San Francisco, CA", "value": "San Francisco, CA" },
  { "title": "Indianapolis, IN", "value": "Indianapolis, IN" },
  { "title": "Columbus, OH", "value": "Columbus, OH" },
  { "title": "Fort Worth, TX", "value": "Fort Worth, TX" },
  { "title": "Charlotte, NC", "value": "Charlotte, NC" },
  { "title": "Detroit, MI", "value": "Detroit, MI" },
  { "title": "El Paso, TX", "value": "El Paso, TX" },
  { "title": "Memphis, TN", "value": "Memphis, TN" },
  { "title": "Boston, MA", "value": "Boston, MA" },
  { "title": "Seattle, WA", "value": "Seattle, WA" },
  { "title": "Denver, CO", "value": "Denver, CO" },
  { "title": "Washington, DC", "value": "Washington, DC" },
  { "title": "Nashville, TN", "value": "Nashville, TN" },
  { "title": "Baltimore, MD", "value": "Baltimore, MD" },
  { "title": "Oklahoma City, OK", "value": "Oklahoma City, OK" },
  { "title": "Las Vegas, NV", "value": "Las Vegas, NV" },
  { "title": "Louisville, KY", "value": "Louisville, KY" },
  { "title": "Milwaukee, WI", "value": "Milwaukee, WI" },
  { "title": "Albuquerque, NM", "value": "Albuquerque, NM" },
  { "title": "Tucson, AZ", "value": "Tucson, AZ" },
  { "title": "Fresno, CA", "value": "Fresno, CA" },
  { "title": "Sacramento, CA", "value": "Sacramento, CA" },
  { "title": "Kansas City, MO", "value": "Kansas City, MO" },
  { "title": "Mesa, AZ", "value": "Mesa, AZ" },
  { "title": "Atlanta, GA", "value": "Atlanta, GA" },
  { "title": "Colorado Springs, CO", "value": "Colorado Springs, CO" },
  { "title": "Virginia Beach, VA", "value": "Virginia Beach, VA" },
  { "title": "Raleigh, NC", "value": "Raleigh, NC" },
  { "title": "Omaha, NE", "value": "Omaha, NE" },
  { "title": "Miami, FL", "value": "Miami, FL" },
  { "title": "Cleveland, OH", "value": "Cleveland, OH" },
  { "title": "Tulsa, OK", "value": "Tulsa, OK" },
  { "title": "Oakland, CA", "value": "Oakland, CA" },
  { "title": "Minneapolis, MN", "value": "Minneapolis, MN" },
  { "title": "Wichita, KS", "value": "Wichita, KS" },
  { "title": "Arlington, TX", "value": "Arlington, TX" },
  { "title": "Bakersfield, CA", "value": "Bakersfield, CA" },
  { "title": "Tampa, FL", "value": "Tampa, FL" },
  { "title": "Aurora, CO", "value": "Aurora, CO" },
  { "title": "Honolulu, HI", "value": "Honolulu, HI" },
  { "title": "Toronto, ON", "value": "Toronto, ON" }
]

export default cities
